name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    env:
      BOOST_VERSION: 1.80.0
      BOOST_VERSION_UB: 1_80_0
      LEDGER_VERSION: 3.2.1

    steps:
      - name: Cache boost build
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: boost
          key: boost-${{ env.BOOST_VERSION }}

      - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
        name: Build boost
        run: |
          curl -LO "https://boostorg.jfrog.io/artifactory/main/release/$env:BOOST_VERSION/source/boost_$env:BOOST_VERSION_UB.7z"
          7z x "boost_$env:BOOST_VERSION_UB.7z"
          Rename-Item "boost_$env:BOOST_VERSION_UB" boost
          cd boost
          .\bootstrap.bat
          .\b2.exe link=static runtime-link=static threading=multi --layout=versioned

      - name: Checkout MPIR
        uses: actions/checkout@v2
        with:
          repository: BrianGladman/mpir
          ref: 33be9007f95b85230da2330ef3ed525896370cc2
          path: mpir

      - name: Build MPIR
        run: |
          cd mpir\msvc\vs22
          .\msbuild.bat gc LIB Win32 Release

      - name: Checkout MPFR
        uses: actions/checkout@v2
        with:
          repository: BrianGladman/mpfr
          ref: b51386896b8bffc11e4b30706c5ec3e64858e16a
          path: mpfr

      - name: Build MPFR
        run: |
          cd mpfr\build.vs22\lib_mpfr
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release lib_mpfr.vcxproj

      - name: Checkout Ledger
        uses: actions/checkout@v2
        with:
          repository: ledger/ledger
          ref: cccb827886773066665e99df4a4ecec4ab5bda14
          path: ledger

      - name: Build Ledger
        id: build
        run: |
          cd ledger
          $GITCOMMIT_FULL = git rev-parse HEAD
          cmake `
          	-DCMAKE_BUILD_TYPE:STRING="Release" `
          	-DBUILD_LIBRARY=OFF `
          	-DMPFR_LIB:FILEPATH="../../mpfr/build.vs22/lib/Win32/Release/mpfr" `
          	-DGMP_LIB:FILEPATH="../../mpir/lib/win32/Release/mpir" `
          	-DMPFR_PATH:PATH="../mpfr/lib/Win32/Release" `
          	-DGMP_PATH:PATH="../mpir/lib/win32/Release" `
          	-DBUILD_DOCS:BOOL="0" `
          	-DHAVE_GETPWUID:BOOL="0" `
          	-DHAVE_GETPWNAM:BOOL="0" `
          	-DHAVE_ISATTY:BOOL="0" `
          	-DBOOST_ROOT:PATH="../boost/" `
          	-DBoost_USE_STATIC_LIBS:BOOL="1" `
          	-DCMAKE_CXX_FLAGS_RELEASE:STRING="/MT /Zi /Ob0 /Od" `
          	-A Win32 `
          	-G "Visual Studio 17"
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release src\ledger.vcxproj
          Write-Output "::set-output name=commit::$GITCOMMIT_FULL"

      - name: Archive
        id: archive
        run: |
          cd ledger\Release
          Compress-Archive -Path ledger.exe -DestinationPath ledger-v${{ env.LEDGER_VERSION }}.zip
          $ARTIFACT_HASH = (Get-FileHash -Algorithm SHA256 ledger-v${{ env.LEDGER_VERSION }}.zip).Hash
          "$ARTIFACT_HASH  ledger-v${{ env.LEDGER_VERSION }}.zip"| Out-File -Encoding ascii -File sha256sum.txt
          Write-Output "::set-output name=hash::$ARTIFACT_HASH"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ledger/Release/ledger-v${{ env.LEDGER_VERSION }}.zip,ledger/Release/sha256sum.txt"
          artifactContentType: application/octet-stream
          name: Ledger v${{ env.LEDGER_VERSION }}
          body: |
            Ledger binary for Windows.

            Built https://github.com/ledger/ledger at commit `${{ steps.build.outputs.commit }}`.

            | File | SHA-256 sum |
            | ---  | ---         |
            | ledger.exe | `${{ steps.archive.outputs.hash }}` |
          token: ${{ secrets.GITHUB_TOKEN }}
